name: project deployment
on:
  push:
    branches: [main]
jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    steps:
      - name: run ssh 
        uses: appleboy/ssh-action@v1
        with:
          host: 183.101.189.204
          username: test
          password: qwer1234
          port: 22
          script: |
            rm -rf ./demo30
            git clone https://github.com/ddarahakit2025/demo30
            chmod 755 ./demo30/gradlew
            ./demo30/gradlew bootJar
            docker build --tag ddarahakit2025/back:latest ./demo30
            
